все тесты локально прошли
Maxrovij/java-explore-with-me pull request #3
Opened 2022-11-06 10:31 UTC by Maxrovij

2022-11-07 06:37 UTC, sergeymamonov requested changes

2022-11-07 06:37 UTC, sergeymamonov commented on ewmservice/src/main/java/ru/practicum/explorewithme/exceptions/ExceptionsHandler.java
> +
Можно добавить еще обработку рантайм ошибки.

2022-11-07 06:37 UTC, sergeymamonov commented on stats/src/main/resources/schema.sql
> +    app      VARCHAR   NOT NULL,
Размер varchar должен быть ограничен.

2022-11-07 06:37 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/explorewithme/exceptions/ExceptionsHandler.java
> +    }
И здесь лучше добавить обработку рантайм ошибки.

2022-11-07 16:10 UTC, Maxrovij commented on ewmservice/src/main/java/ru/practicum/explorewithme/exceptions/ExceptionsHandler.java
> +
+

2022-11-07 16:11 UTC, Maxrovij commented on stats/src/main/java/ru/practicum/explorewithme/exceptions/ExceptionsHandler.java
> +    }
+

2022-11-07 16:11 UTC, Maxrovij commented on stats/src/main/resources/schema.sql
> +    app      VARCHAR   NOT NULL,
+

2022-11-08 15:20 UTC, sergeymamonov approved these changes

2022-11-08 15:20 UTC, sergeymamonov commented on ewmservice/src/main/java/ru/practicum/explorewithme/exceptions/ExceptionsHandler.java
> +                HttpStatus.CONFLICT,
Проверьте здесь, строки 45 и 48.

2022-11-08 15:20 UTC, sergeymamonov commented on ewmservice/src/main/java/ru/practicum/explorewithme/exceptions/ExceptionsHandler.java
> +
Имеется в виду добавить обработку handleAll(Exception ex) 

HttpStatus.INTERNAL_SERVER_ERROR

Во втором сервисе аналогично.

2022-11-08 15:36 UTC, merged